# Generated by Django 6.0.7 on 2026-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='react',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='react',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
