# Generated by Django 6.0.7 on 2026-07-29 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_created_at_remove_react_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='views',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
