# Generated by Django 6.0.7 on 2026-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_react_created_at_react_updated_at_alter_react_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='react',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
