# Generated by Django 6.0.7 on 2026-07-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_react_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='title',
        ),
    ]
