# Generated by Django 6.0.7 on 2026-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_department_react_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
