# Generated by Django 6.0.7 on 2026-08-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_react_author_alter_react_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
