# Generated by Django 6.0.7 on 2026-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='content',
            field=models.TextField(),
        ),
    ]
