# Generated by Django 6.0.7 on 2026-08-05 14:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_react_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
