# Generated by Django 6.0.7 on 2026-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
