# Generated by Django 6.0.7 on 2026-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_populate_react_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
